import io
import struct

import pytest

from visioncortex.rtp_opus import OggOpus, Opus, delta, parse


def test_parse_rtp_header_and_extensions():
    payload = b"opus"
    packet = struct.pack("!BBHIIHH", 0x90, 111, 12, 100, 7, 0xBEDE, 0) + payload
    value = parse(packet, 123456)
    assert value.sequence == 12
    assert value.timestamp == 100
    assert value.ssrc == 7
    assert value.payload == payload
    assert value.received_us == 123456


def test_parse_rejects_wrong_payload_type():
    with pytest.raises(ValueError):
        parse(struct.pack("!BBHII", 0x80, 96, 1, 2, 3) + b"x", 1)


def test_rtp_wrap_delta():
    assert delta(1, 65535, 16) == 2
    assert delta(1, 0xFFFFFFFF, 32) == 2


def test_ogg_opus_pages_are_valid_and_preserve_packet_payload():
    codec = Opus()
    # This is a valid 20 ms mono Opus packet generated by the recorder codec.
    packet = bytes.fromhex(
        "7808a890249ba702220acc6b57e2985f1f77d9298b1f8e14ee703271f95ebb81"
        "d6224bee576d5c33df73e9c478a447f84da422970951327cd60f193ab6bef954"
        "51f6d17b905863f8ab45178f2579dcb2"
    )
    samples, channels = codec.info(packet)
    assert channels == 1
    output = io.BytesIO()
    writer = OggOpus(output, 7, channels)
    writer.write(packet, samples)
    writer.finish()
    data = output.getvalue()
    assert data.startswith(b"OggS")
    assert b"OpusHead" in data
    assert packet in data
