experiment_id: VC-E3413743-VALIDATION
views:
  - view_id: lubancat-e8cc0cb3_cam01
    role: first_person
    video: D:/VisionCortexData/runtime/objects/e3413743057a32e5a54c2306468bbcbc/lubancat-e8cc0cb3_cam01/video.mp4
    timestamps_csv: D:/VisionCortexData/runtime/objects/e3413743057a32e5a54c2306468bbcbc/lubancat-e8cc0cb3_cam01/clock.csv
  - view_id: orangepi5pro-ab748372_cam01
    role: third_person
    video: D:/VisionCortexData/runtime/objects/e3413743057a32e5a54c2306468bbcbc/orangepi5pro-ab748372_cam01/video.mp4
    timestamps_csv: D:/VisionCortexData/runtime/objects/e3413743057a32e5a54c2306468bbcbc/orangepi5pro-ab748372_cam01/clock.csv
  - view_id: orangepi5pro-b439137c_cam02
    role: third_person
    video: D:/VisionCortexData/runtime/objects/e3413743057a32e5a54c2306468bbcbc/orangepi5pro-b439137c_cam02/video.mp4
    timestamps_csv: D:/VisionCortexData/runtime/objects/e3413743057a32e5a54c2306468bbcbc/orangepi5pro-b439137c_cam02/clock.csv
  - view_id: orangepi5pro-d12a4719_cam01
    role: third_person
    video: D:/VisionCortexData/runtime/objects/e3413743057a32e5a54c2306468bbcbc/orangepi5pro-d12a4719_cam01/video.mp4
    timestamps_csv: D:/VisionCortexData/runtime/objects/e3413743057a32e5a54c2306468bbcbc/orangepi5pro-d12a4719_cam01/clock.csv
  - view_id: orangepi5pro-fe0ec3fe_cam01
    role: third_person
    video: D:/VisionCortexData/runtime/objects/e3413743057a32e5a54c2306468bbcbc/orangepi5pro-fe0ec3fe_cam01/video.mp4
    timestamps_csv: D:/VisionCortexData/runtime/objects/e3413743057a32e5a54c2306468bbcbc/orangepi5pro-fe0ec3fe_cam01/clock.csv
  - view_id: rk3588-ubuntu_cam01
    role: third_person
    video: D:/VisionCortexData/runtime/objects/e3413743057a32e5a54c2306468bbcbc/rk3588-ubuntu_cam01/video.mp4
    timestamps_csv: D:/VisionCortexData/runtime/objects/e3413743057a32e5a54c2306468bbcbc/rk3588-ubuntu_cam01/clock.csv
